services:
  laravel_app:
    container_name: laravel_guess_who
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres_guess_who:
        condition: service_healthy
    volumes:
      - .:/var/www/html
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    command: [ "sh", "-c", "
          php artisan migrate --force &&
          php artisan db:seed --force &&
          php artisan serve --host=0.0.0.0 --port=8000
    " ]

  postgres_guess_who:
    container_name: postgres_guess_who
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guess_who
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "postgres", "-U", "postgres" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: unless-stopped

volumes:
  postgres_data:
