version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    volumes:
      - ./laraveltest:/var/www/html

    working_dir: /var/www/html/laraveltest  
    depends_on:
      - mysql
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/app
    working_dir: /app/laraveltest  
    entrypoint: ["composer"]

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - laravel
    ports:
      - "3306:3306"

  webserver:
    image: nginx:latest
    container_name: laravel_webserver
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
       - ./laraveltest:/var/www/html
    depends_on:
      - app
    ports:
      - "8080:80"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
