version: "3.8"

networks:
  cloud-network:
    external: true

volumes:
  identity-pg-volume:

services:
  identity-pg:
    container_name: identity-pg
    networks:
      - cloud-network
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: itu16
      POSTGRES_DB: guess_who
    volumes:
      - identity-pg-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "postgres", "-U", "postgres" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  identity-app:
    container_name: identity-app
    networks:
      - cloud-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      identity-pg:
        condition: service_healthy
    volumes:
      - .:/var/www/html
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    command: [ "sh", "-c", "
          php artisan l5-swagger:generate &&
          php artisan migrate --force &&
          php artisan db:seed --force &&
          php artisan serve --host=0.0.0.0 --port=8000
    " ]
